obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.08, 0.05], [0.08, -0.05], [-0.08, -0.05], [-0.08, 0.05]]
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}